function [dfdx,dfdu] = attackerJacobiansCartesian(in1,in2,in3)
%attackerJacobiansCartesian
%    [DFDX,DFDU] = attackerJacobiansCartesian(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Apr-2024 01:37:09

%Generated by scrapForJacobianFunctionAttacker.m

sysParams1 = in3(1,:);
sysParams2 = in3(2,:);
uIn2 = in2(2,:);
xStateFull3 = in1(3,:);
t2 = cos(xStateFull3);
t3 = sin(xStateFull3);
t4 = 1.0./sysParams1;
dfdx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*t4.*uIn2,t2.*t4.*uIn2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,6]);
if nargout > 1
    dfdu = reshape([0.0,0.0,0.0,0.0,0.0,1.0./sysParams2,0.0,0.0,0.0,t2.*t4,t3.*t4,0.0],[6,2]);
end
end
